INSERT INTO MANUFACTURER(COMPANY, NATIONALITY)
VALUES ('Budweiser', 'German');
INSERT INTO MANUFACTURER(COMPANY, NATIONALITY)
VALUES ('Double Nickel Brewing Company', 'German');
INSERT INTO MANUFACTURER(COMPANY, NATIONALITY)
VALUES ('Corona', 'German');
INSERT INTO MANUFACTURER(COMPANY, NATIONALITY)
VALUES ('Heineken', 'German');
INSERT INTO MANUFACTURER(COMPANY, NATIONALITY)
VALUES ('Aloha Beer Company', 'German');

INSERT INTO BEER(NAME, BEERTYPE, GRADUATION, DESCRIPTION, MANUFACTURER_ID)
values ('Bud Light', 'Craft Beer', 'Congrats Grad Beer', '', 1);
